USERS_API_URL = ROOT + '/users'
USER_AUTHENTICATION_URL = ROOT + '/users/logon'
USER_LOGOFF_URL = ROOT + '/users/logoff'
USER_DPSEARCH_ADMIN_API_URL = ROOT + '/users/admin'
USER_ROLE_MAPPING_API_URL = ROOT + '/users/role_mappings'
